### ISSUE TITLE
Could not find "client" in the context or passed in as an option.

### ISSUE THREAD

**Issue by ParallelUniv3rse** [lifeiscontent/storybook-addon-apollo-client#106]
Previous closed issue: #52 

This happens when you're already exporting `decorators` from your own preview.js file. 

the `withApolloClient` then does not get merged into the decorators and instead gets overwritten by my custom `decorators` field. 

The result is the Apollo provider is missing. 

Possible solution: 

importing the decorators from this package in my own preview.js and spreading them into my config. 
This does not work though because when importing i get a `Default condition should be last one` error due to the order of paths in the `exports` field in this package's package.json file. 

Using Apollo Client 3.x and Storybook 7.x with storybook-addon-apollo-client 5.0.0

**Comment by lifeiscontent** [comment]
@ParallelUniv3rse this should be fixed now, let me know if you run into any issues!

**Comment by marcosdiasdev** [comment]
I've had the same problem today and had to apply the fix suggested by @ParallelUniv3rse to get it to work in my setup. I'm using the following versions:

```
"@storybook/react": "8.6.14",
"react": "^17.0.2",
"storybook-addon-apollo-client": "^8.1.2",
```

Tried passing `MockedProvider` to the `apolloClient` key in `parameters` and also tried passing `MockedProvider` as a context provider in my decorators without success.
