### ISSUE TITLE
Please support "maxUsageCount" for reusing mock in the Storybook

### ISSUE THREAD

**Issue by LaurenceHo** [lifeiscontent/storybook-addon-apollo-client#108]
In Apollo client v3.10.0-alpha1, it supports reusing mock when setting ["maxUsageCount"](https://github.com/apollographql/apollo-client/commit/4d64a6fa2ad5abe6f7f172c164f5e1fc2cb89829#diff-230adf4ef83899859699a3fdbf7e5b0499c8ab0702469a173ad0f030104772f2R175), however, this attribute doesn't work in this Storybook addon.  It'd be great if this addon can support this feature. Thanks a lot.

**Comment by lifeiscontent** [comment]
@LaurenceHo file an issue in Apollo, there's nothing stopping this API for supporting it, it must not be exposed in their mock client.

**Comment by LaurenceHo** [comment]
> @LaurenceHo file an issue in Apollo, there's nothing stopping this API for supporting it, it must not be exposed in their mock client.

Thanks, I will ask them.

**Comment by lifeiscontent** [comment]
@LaurenceHo I'm going to close this for now, feel free to open if you have any other issues I can help with.

**Comment by LaurenceHo** [comment]
> @LaurenceHo I'm going to close this for now, feel free to open if you have any other issues I can help with.

All good. After I upgraded Apollo client to 3.90, it's working now. :)
