### ISSUE TITLE
Missing preset file

### ISSUE THREAD

**Issue by tiagoernst** [lifeiscontent/storybook-addon-apollo-client#119]
When using the addon with storybook 8 I get an error saying:
```
Please check whether your setup is correct, the Storybook dependencies (and their peer dependencies) are installed correctly and there are no package version clashes.

If you believe this is a bug, please open an issue on Github.

Error: Cannot find module './dist/preset.cjs'
Require stack:
- ***/node_modules/storybook-addon-apollo-client/preset.js
- ***/node_modules/@storybook/core-common/dist/index.js
```

**Comment by tiagoernst** [comment]
Never mind, it was caused by modification when using storybook migration tool

**Comment by pierceray** [comment]
What did you do to fix this?  I'm having the same issue while trying to migrate.

**Comment by tiagoernst** [comment]
Hey @pierceray storybook migration had added a helper function `getAbsolutePath` to import the addons that was actually not necessary. Just removing it and putting the name of the addon package on the storybook was enough and removed the error

**Comment by pierceray** [comment]
Thank you.  That's also the solution I had found.

**Comment by mrbinky3000** [comment]
@tiagoernst just saved me a ton of time. I wouldn't have found this out on my own for hours or longer. This should be added to the main docs for this plugin.
