### ISSUE TITLE
Queries with fragments do not get returned properly

### ISSUE THREAD

**Issue by khelif96** [lifeiscontent/storybook-addon-apollo-client#17]
I am unable to get a mocked response from a query with a fragment in it. 
If i dont use a fragment the response gets returned correctly. I am able to use the query with the fragment outside of storybook. 
EXAMPLE:
```
query UserProfile {
    name {
         ...Name
     }
     gender
}
fragment Name on User {
    firstName
    lastName
}
```
mocked response:
```
user : {
 name: {},
 gender: "male",
}
```

Desired Response:
```
user : {
 name: {
     firstName: "John",
     lastName: "Doe"
 },
 gender: "male",
}
```

**Comment by lifeiscontent** [comment]
@khelif96 Can you share a reproduction?

**Comment by kaykdm** [comment]
@khelif96 
I faced the same issue, and I solved this by adding `__typename` field to data like this.
https://github.com/lifeiscontent/realworld/blob/9a15d2ef0b3638e2e3688bd69f46759d94965502/web/src/containers/editor-page/index.stories.js#L23

I think this needs to be documented.

**Comment by lifeiscontent** [comment]
@kaykdm it is documented. Please look at the docs for MockedProvider. This addon is just an visual interface for it.
