### ISSUE TITLE
Any plan for this library to work with vite builder ?

### ISSUE THREAD

**Issue by tiffanynguyen0211** [lifeiscontent/storybook-addon-apollo-client#46]
Error when using vite builder : 
<img width="731" alt="Screen Shot 2021-08-17 at 10 30 55 AM" src="https://user-images.githubusercontent.com/13669114/129638123-3fc16835-4149-4a95-b14a-21a2abc61826.png">
suspected cause the library needs esm build, not sure if there any plan to implement one?

**Comment by lifeiscontent** [comment]
@tiffanynguyen0211 if you can put together a sandbox app with storybook running for me to test it out (I don't know about vite) I'll try to get it working.

**Comment by lifeiscontent** [comment]
@tiffanynguyen0211 any updates here?

**Comment by tiffanynguyen0211** [comment]
@lifeiscontent sorry I was not very exeprience of setting up storybook on codesandbox so I ended up setting up a [git repo using Vite + React + Storybook with Vite + Apollo](https://github.com/tiffanynguyen0211/react-vite-storybook/tree/apollo-implement) instead. Feel free to clone it and you will see the error when you trying to start up storybook
![Screen Shot 2021-09-06 at 1 09 21 PM](https://user-images.githubusercontent.com/13669114/132147380-4533d6d4-e8b4-48e9-a098-66f36b9fb706.png)

**Comment by lifeiscontent** [comment]
@tiffanynguyen0211 awesome, thank you, I'll take a look over the weekend.

**Comment by lifeiscontent** [comment]
@tiffanynguyen0211 sorry for the late response. I've looked into it, and it seems you're right. I'd have to release with both `cjs` and `esm` I'm gonna talk with the storybook team and see what the best possible way to support this looks like.

**Comment by brettdewoody** [comment]
This would be great to get working. Any way I can help?

**Comment by lifeiscontent** [comment]
@brettdewoody sure! we would need to update the imports to include all file extensions for relative imports, export for esm and cjs and modify the package.json to update the new paths.

some context:

previously when webpack was the only thing around, it was cjs everywhere, but vite operates via esm so that's where this issue propped up 😅 

let me know if you need any more context, I can help you if you've got time to move forward with this effort.

**Comment by lifeiscontent** [comment]
in the next version of storybook this seems to be working so I'm going to close this for now, if anyone has issues or wants me to add support for a specific version of storybook, please let me know here so I can test accordingly.
