### ISSUE TITLE
Mockprovider won't return the right mock for storybook with multiple stories

### ISSUE THREAD

**Issue by teseo** [lifeiscontent/storybook-addon-apollo-client#62]
Hello,

Addon version: `4.0.9`
Storybook version: `6.4.3`
Apollo version: `3.4.17`

I have a storybook that contains more than one story. 

In the storybook web site you can navigate both stories. but it will only have the mock of the first story selected when you loaded the page. If you want to check the other story with the right data, you need to refresh the page every time you select a story

The code looks like this:
```
const stripePromise = loadStripe(stripePublicKey);

export default {
  title: "Category/Component",
  component: Component,
  parameters: {
    apolloClient: {
      mocks: createMockWithEmptyResponse,
    },
  },
};

export const ComponentWithEmptyResults = () => {
  const props = {
    prop1: "test",
    prop2: "test"
  };

  return (
    <div
      style={{
        display: "flex",
        textAlign: "center",
        justifyContent: "center",
        flexDirection: "column",
      }}
    >
      <Elements stripe={stripePromise}>
        <Component {...props} />
      </Elements>
    </div>
  );
};

export const ComponentWithResults = () => {
  const props = {
    prop1: "test",
    prop2: "test"
  };
  return (
    <div
      style={{
        display: "flex",
        textAlign: "center",
        justifyContent: "center",
        flexDirection: "column",
      }}
    >
      <Elements stripe={stripePromise}>
        <PaymentCardDepositForm {...props} />
      </Elements>
    </div>
  );
};

ComponentWithResults.parameters = {
  apolloClient: {
    mocks: createMockWithData,
  },
};
```

Is there anything that I'm doing wrong? Is this functionality actually implemented?

Many thanks for the hard work!

**Comment by lifeiscontent** [comment]
@teseo I'm guessing you're wanting to do something like this: https://5fcdd27b2771900021fc381e-rdqduazmqw.chromatic.com/?path=/story/containers-articlecomments--can-create-comment

in this example you can write a comment that triggers a mutation using the phrase "Hello world" and it will populate the components with a stubbed response.

let me know if this isn't what you want, happy to help, I'm just not sure what you're trying to solve exactly.

you can find the source code for these stories here: https://github.com/lifeiscontent/realworld

**Comment by teseo** [comment]
@lifeiscontent thanks a lot for your prompt response. Not really. Having the example that you shared, Imagine that you have a component that renders an article list. Then you want to have that component to render a stubbed response with, let's say, 3 articles in one story, and then another story with the component rendering an empty list of articles and displaying a default text saying "no articles to be displayed".

In this case you would have two stories and each one will have two stubbed responses. One with 3 articles and another one empty. In my case, unless I refresh the page, my component will only render three articles, regarding of the story I navigate.

**Comment by lifeiscontent** [comment]
@teseo I realize you might be having the same issue as https://github.com/lifeiscontent/storybook-addon-apollo-client/issues/82 please have a look there to see if it fixes your issue, I'm going to close this issue for now, but if you think its not the same, happy to reopen and discuss further.
