### ISSUE TITLE
MockedProvider doesn't take variables

### ISSUE THREAD

**Issue by JohannesKlauss** [lifeiscontent/storybook-addon-apollo-client#7]
Everything works fine for queries without variables, but as soon as I try to include variables, the MockedProvider doesn't see them:

<img width="936" alt="Bildschirmfoto 2020-10-23 um 17 24 42" src="https://user-images.githubusercontent.com/6214415/97024686-62459f00-1557-11eb-8984-d2ef29fcbf03.png">

In the screenshot you can see that I am using variables in my mock, but the Provider says I didn't pass any.

This is my setup for the story:
```tsx
export default {
  title: 'molecules/feed/createFeedItem/FeedItemAudioPreview',
  component: FeedItemAudioPreview,
  decorators: [withApolloClient]
};

// Each story then reuses that template
export const Default = Template.bind({});

Default.args = {};

console.log('mock', mockApolloResult<MixdownQuery, MixdownQueryVariables>(MixdownDocument, MixdownMock, {id: 'dasdas'}));

Default.parameters = mockApollo([
  mockApolloResult<MixdownQuery, MixdownQueryVariables>(MixdownDocument, MixdownMock, {id: 'dasdas'})
]);
```

Am I missing something?

**Comment by lifeiscontent** [comment]
@JohannesKlauss it looks like you're not passing any variables. I'm not familiar with the syntax you're using. what is `mockApollo`?

if you use something like `useQuery` the signature is 

```js
useQuery(GraphQLDocument, {
  variables: {
    id: 'dasdaas'
  }
});
```

could that be the reason?

**Comment by JohannesKlauss** [comment]
@lifeiscontent I am passing variables. `mockApollo` is just a helper function that returns the mock for me. In the screenshot you can see that I am creating a mock with a variables object inside the request object, but for some reason the mocked provider doesn't see the variables.

**Comment by JohannesKlauss** [comment]
Sorry, I just realized that the actually query that runs against the MockerProvider didn't have a variable assigned, my bad.
