### ISSUE TITLE
Mocking mutations?

### ISSUE THREAD

**Issue by mshick** [lifeiscontent/storybook-addon-apollo-client#76]
Am I doing something wrong, or is mocking mutations not possible? Is there a major blocker to implementing a feature like that?

I've attempted a config like the following, but it generates Storybook errors.

```
{
  parameters: {
    apolloClient: {
      mocks: [
        {
          request: {
            mutation: CreateCustomerMutation,
            variables: { email: 'foo@bar.com', password: 'test1234' }
          },
          result: {
            data: {
              customerCreate: {
                customer: {
                  id: 'foo'
                }
              }
            }
          }
        }
      ]
    }
  }
}
```

**Comment by mshick** [comment]
I also tried with `query: CreateCustomerMutation` of course, but it fails to match the request.

**Comment by lifeiscontent** [comment]
@mshick you can see a working example of a mutation here: https://github.com/lifeiscontent/realworld/blob/master/web/src/containers/article-comments/index.stories.js please open another issue if this doesn't solve it for you.
