### ISSUE TITLE
Missing peer dependency "graphql"

### ISSUE THREAD

**Issue by magnattic** [lifeiscontent/storybook-addon-apollo-client#79]
In the latest version you removed almost all peerDependencies.

This leads to errors under yarn in pnp mode:

>ModuleNotFoundError: Module not found: Error: Can't resolve 'graphql' in '/srv/.yarn/__virtual__/storybook-addon-apollo-client-virtual-7ad323f3d6/0/cache/storybook-addon-apollo-client-npm-4.0.12-b03787ed5b-6099fa8d0b.zip/node_modules/storybook-addon-apollo-client/dist'

**Comment by lifeiscontent** [comment]
@magnattic you should have graphql as a dependency in your own project, does that not work? Sorry. I'm not familiar with yarn pnp.

**Comment by magnattic** [comment]
Yes, that's what a peerDependency is. :) But if you expect `graphql` to be installed, you still have to declare it in your package.json. Which you don't do anymore. 

With `npm` this still works if the package exists somewhere in your node_modules, but yarn pnp is more strict and only allows you to access this package if you declare it. (which makes sense)

**Comment by lifeiscontent** [comment]
@magnattic yeah, fair enough, would you mind creating a PR? If not I'll try to get to it this weekend.

**Comment by lifeiscontent** [comment]
@magnattic fixed in latest release, please take a look :)
