### ISSUE TITLE
How can I get data from readFragment?

### ISSUE THREAD

**Issue by msko89** [lifeiscontent/storybook-addon-apollo-client#81]
Hello,
I want to get data from readFragment.

<br />
<br />

Example:

I use codegen to use apollo-client custom hooks.

The code below is the apollo-client hook to query the theme.
Running useGetMyThemeQuery will cache MyTheme, Style and Page.

```
const { loading, error, data } = useGetMyThemeQuery({
  variables: { myThemeId },
});
```

<br />
<br />

The Graphql schema looks like this:

```
query GetMyTheme($myThemeId: ID!) {
  myTheme(myThemeId: $myThemeId) {
    ...MyTheme
  }
}

fragment MyTheme on MyTheme {
  id
  style {
    ...Style
  }
}

fragment Style on Style {
  id
  pages {
    ...Page
  }
}

fragment Page on Page {
  id
  name
}
```

<br />
<br />

Below is the fixture data.

```
// fixture.ts
import { MyTheme } from './types';

export const myTheme: MyTheme = {
  "__typename": "MyTheme",
  "id": "mytheme1",
  "style": {
    "__typename": "Style",
    "id": "style1",
    "pages": [
      {
        "__typename": "Page",
        "id": "page1",
        "name": "Home",
      },
      {
        "__typename": "Page",
        "id": "page2",
        "name": "About",
      },
      {
        "__typename": "Page",
        "id": "page3",
        "name": "Shop",
      }
    ],
  },
};

```

<br />
<br />

When you run the project, the Page is cached as follows.

![스크린샷 2022-08-17 오후 11 02 49](https://user-images.githubusercontent.com/50323309/185154137-f435b1a2-51db-4e2d-a69d-194bc9ab4ccf.png)

<br />
<br />

However, I can't get the data of the cached readFragment from the storybook.
(I can get data with custom hook.)

```
// PageItem.tsx
const data = client.readFragment<Page>({
  id: `Page:${pageId}`,
  fragment: PageFragmentDoc,
});

console.log(data); // null
```

Is there a way to get the cached data into a readFragment?

Thank you.

---

Versions
System:
OS: macOS 12.3.1

Binaries:
Node: 16.15.1
Yarn: 1.22.17
npm: 8.11.0

npmPackages:
@apollo/client: ^3.6.9 => 3.6.9
storybook-addon-apollo-client: ^4.0.12 => 4.0.12

**Comment by chidiwilliams** [comment]
How did you fix this?
