### ISSUE TITLE
Using two different parts of the same graph result in errors

### ISSUE THREAD

**Issue by erwan-joly** [lifeiscontent/storybook-addon-apollo-client#82]
I finally been able to reproduce the error I was talking about here https://github.com/lifeiscontent/storybook-addon-apollo-client/issues/44

here the code to repro:
https://github.com/erwan-joly/GraphqlMockErrorRepro

not sure what is happening and how to fix it but it seems to occurs when two queries on the same component share different parts of the same graph type @lifeiscontent

**Comment by lifeiscontent** [comment]
@erwan-joly nice find, I'll dig into this later this weekend, thank you!

**Comment by lifeiscontent** [comment]
FWI I suspect this might be an issue with `@apollo/client` itself, I'm using their MockApolloClient utility and I'm guessing this is an edge case they didn't think of.

**Comment by lifeiscontent** [comment]
@erwan-joly figured it out, and it was as I suspected. there are two different solutions for solving this problem as outlined here: https://stackoverflow.com/questions/66455345/apollos-mockedprovider-doenst-work-when-a-component-has-multiple-usequerys I tested the first option and that worked, but I'd suspect the second option works as well, you should probably determine which option would work better for you to not give you false positives.

that being said, I've also taken the type to update your repro with a working solution here: https://github.com/erwan-joly/GraphqlMockErrorRepro/pull/1

**Comment by lifeiscontent** [comment]
I'm going to close this issue now but feel free to comment if you have any issues, or open another issue if you find something else!

**Comment by erwan-joly** [comment]
Thanks 👍 option 1 seems good!
