### ISSUE TITLE
Change to ranged Storybook dependency versions

### ISSUE THREAD

**Issue by aaronadamsCA** [lifeiscontent/storybook-addon-apollo-client#85]
https://github.com/lifeiscontent/storybook-addon-apollo-client/blob/e233f9896153af15dde9325538368df6bd7ecf16/package.json#L7-L11

This is causing duplicate versions of Storybook in my repository. It would be better to ship with version ranges.

It looks like these were pinned here, possibly by mistake: ad56d491095e75a337711f10800ed1d9080e1d99

**Comment by lifeiscontent** [comment]
@aaronadamsCA @etrejos can you test the latest release to see if your issues are fixed?

**Comment by etrejos** [comment]
Hi @lifeiscontent I can confirm that the issue has been solved in `^4.0.14`.

**Comment by lifeiscontent** [comment]
@etrejos thank you!
