### ISSUE TITLE
Global mocks not being merged

### ISSUE THREAD

**Issue by octavien-mural** [lifeiscontent/storybook-addon-apollo-client#93]
I've set up the mocked apollo client as per the docs, and I have a global query that is required throughout the application which I have set in my `preview.tsx` file.

I noticed that this query gets correctly picked up by any story that doesn't have its own mocks, but stories that do have mocks are requiring me to duplicate this same request within the story file itself. 

Why doesn't the addon automatically merge the mocks?

**Comment by octavien-mural** [comment]
Thank you for the quick reply! I agree that storybook should be merging the parameters, but it might be having issues since its trying to merge an object. (not too sure about how this works)

For our use case, we are currently mocking queries that are specific to individual stories, but we also have higher order components/providers that wrap our entire application and make their own queries. In these cases, it would be preferable to simply declare these mocks once at the highest level (ex/ in `preview.tsx`), and have the individual stories inherit these mocks in addition to the ones specific to those stories, instead of having to duplicate these higher level mocks for every single story.  

Another example of this would be the case where we have a single component and story file with multiple stories that share one mocked query, and have a second mocked query specific to each story. In this case, it would be nice to be able to declare the shared mock once in the default export, and then declare the story specific mocks in the story parameters. 

If thats an update that you could provide that would be greatly appreciated, or if its a semi straightforward fix I'd be more than happy to submit a PR myself. In any case please let me know if theres any information I can provide to clarify or anything I can do make things easier on your end!

**Comment by octavien-mural** [comment]
@lifeiscontent soft ping on this :)

**Comment by lifeiscontent** [comment]
@octavien-mural cool, I'll see if I can put something together this week.

**Comment by octavien-mural** [comment]
@lifeiscontent thank you so much, I really appreciate it!

**Comment by lifeiscontent** [comment]
@octavien-mural just curious are you guys hiring? 😄

**Comment by octavien-mural** [comment]
@lifeiscontent at the moment we are not as we're in a strong build phase, but we should be hiring again next month or so !

**Comment by lifeiscontent** [comment]
@octavien-mural can you please take a look at this PR and see if it works for you?

https://github.com/lifeiscontent/storybook-addon-apollo-client/pull/94

you can run this version locally by doing the following:

1. clone storybook-addon-apollo-client
2. cd storybook-addon-apollo-client
3. npm i
4. npm build
5. npm link
6. cd ../your-project
7. npm link storybook-addon-apollo-client

add the mocks you need to the new globalMocks parameter

**Comment by octavien-mural** [comment]
@lifeiscontent thanks for the PR! I tried running locally but running my storybook seems to be failing with:

`ReferenceError: exports is not defined
    at http://localhost:6006/@fs/my-project/storybook-addon-apollo-client/dist/preset/addDecorator.js:2:23`

Would that be an issue with the linking or an issue with the PR?

**Comment by lifeiscontent** [comment]
interesting, are you using vite or webpack to build your storybook?

**Comment by lifeiscontent** [comment]
@octavien-mural interesting, are you using vite or webpack to build your storybook?

**Comment by octavien-mural** [comment]
@lifeiscontent I'm using vite, and i'm also using storybook v7 if that makes a difference

**Comment by lifeiscontent** [comment]
I guess its time to pivot to ES Modules. I created this addon before storybook was using vite so there's probably an issue with vite not supporting commonjs. @octavien-mural would it be possible for you to put a minimal storybook together with vite + apollo? So I can have something to quickly work with.

**Comment by octavien-mural** [comment]
@lifeiscontent Ah ok I see makes sense. I could put one together but wont be able to until later this week when I have more time unfortunately

**Comment by lifeiscontent** [comment]
@octavien-mural no worries, just ping and I'll get to it when I can :)

**Comment by lifeiscontent** [comment]
@octavien-mural friendly bump on this :)

**Comment by octavien-mural** [comment]
@lifeiscontent Hey sorry just now getting to this! Been a busy few weeks, were you able to set up an environment by any chance?

**Comment by lifeiscontent** [comment]
@octavien-mural nope, was waiting on you as currently the addon supports all of my use cases, I'm just trying to help support other usages for users like yourself but I'm currently lacking context on how your setup looks like which could greatly reduce the time to make something that works.

**Comment by lifeiscontent** [comment]
@octavien-mural can you try out the latest version and see if it does what you'd expect?

**Comment by octavien-mural** [comment]
@lifeiscontent Hey there, thanks for the update. Unfortunately it looks like the behavior is the same. I have global mocks in my preview file, but as soon as I add mocks to a story it overrides the global mocks instead of merging them. If it would help we could set up a call to go more in depth on the issue. Unfortunately this issue has greatly limited our ability to create stories since we are having to duplicate so many queries in our stories.

**Comment by octavien-mural** [comment]
@lifeiscontent Hey there, I changed the `mocks` to `globalMocks` in my `preview.tsx` file and it seems to be working as expected, so thank you so much! 

One additional thought, however, its seems like the case where mocks that are applied to a default export are not getting merged properly. This would be for the aforementioned case:

"Another example of this would be the case where we have a single component and story file with multiple stories that share one mocked query, and have a second mocked query specific to each story. In this case, it would be nice to be able to declare the shared mock once in the default export, and then declare the story specific mocks in the story parameters."

Would it be possible to add support for this? Thanks in adavnce!

**Comment by lifeiscontent** [comment]
@octavien-mural is it that they aren't being shown in the apollo panel? or not being run entirely?

**Comment by lifeiscontent** [comment]
can you take a look at this code: https://github.com/lifeiscontent/storybook-addon-apollo-client/blob/master/src/withApolloClient.tsx#L20-L40 and see if you can deduce why its not working for the usecase you're discribing?

**Comment by lifeiscontent** [comment]
for context, the useEffect is sending the results for the stories to the apollo panel and the MockedProvider is sending the mocks into the currently rendered story

**Comment by lifeiscontent** [comment]
@octavien-mural I'm going to close this in favor of using composition, if you want to see an example, take a look at the README.
