### ISSUE TITLE
Add support for Storybook 7

### ISSUE THREAD

**Issue by annidai** [lifeiscontent/storybook-addon-apollo-client#97]
I'm upgrading to use Storybook 7, and this warning is been thrown:
```
[WARN] You (or an addon) are using the 'config' preset field. This has been replaced by 'previewAnnotations' and will be removed in 8.0
```

Is there a plan to support Storybook 7?

**Comment by lifeiscontent** [comment]
@annidai I'm sorry, is there something that is not working for you? this is just a warning that is telling developers that storybook 8 will not work with this addon.

**Comment by annidai** [comment]
It's working for me. Just want to make sure this won't break in the future.

**Comment by lifeiscontent** [comment]
@annidai I already updated this addon to work with storybook 7 during the prerelease, I will do the same when storybook 8 comes out.
